import type { Article } from "./types"

export const websiteArticles: Article[] = [
  {
    number: 13, slug: "weg-zur-eigenen-website", category: "Websites & Schnittstellen",
    title: "Deine eigene Website: Was du wirklich brauchst – und was erstmal nicht.",
    description: "Von einer klaren Idee zur ersten eigenen Seite: Verstehe Domain, Hosting und Code und baue einen kleinen Prototyp, bevor du Verträge abschließt.",
    lead: "Deine Website sollte eine einfache Frage beantworten: Warum sollte jemand gerade mit dir arbeiten? Dafür brauchst du zunächst weder einen Shop noch ein Kundenportal. Eine übersichtliche Seite mit einem verständlichen Angebot und einem klaren nächsten Schritt kann der bessere Start sein. Technik kommt hinzu, wenn sie diesem Ziel dient.",
    result: "Ein eigener, lokal im Browser laufender Website-Prototyp und eine überschaubare Liste der Bausteine für die Veröffentlichung.",
    level: "Einstieg · Website-Grundlagen",
    prerequisites: ["Ein Angebot, eine Zielgruppe und ein gewünschter nächster Schritt", "Ein Computer mit Texteditor und Browser", "Nur erfundene Beispielinhalte für den ersten Entwurf; noch kein Hostingvertrag erforderlich"],
    sections: [
      { id: "ziel", title: "Schreibe zuerst den Satz, den Besucher verstehen sollen.", paragraphs: ["Notiere: „Ich helfe dieser Zielgruppe bei diesem Problem mit dieser Leistung.“ Ergänze einen einzigen nächsten Schritt: anrufen, eine Anfrage senden oder einen Termin vereinbaren. Eine erste Seite braucht keine fünf gleich wichtigen Aufforderungen. Prüfe deinen Satz mit einer Person, die dein Geschäft nicht kennt. Kann sie das Angebot in eigenen Worten wiedergeben?", "Lege danach drei Abschnitte fest: das Problem und dein Angebot, der konkrete Nutzen, der Weg zur Kontaktaufnahme. Verwende nur belegbare Referenzen und eigene oder ausreichend lizenzierte Bilder. Ein professioneller Eindruck entsteht nicht durch erfundene Erfolgszahlen, sondern durch klare Informationen und passende Beispiele."] },
      { id: "bausteine", title: "Adresse, Ablage und Inhalt sind drei verschiedene Dinge.", paragraphs: ["Die Domain ist die Adresse deiner Website. Das Hosting stellt die Seite im Internet bereit. HTML beschreibt die Inhalte, CSS das Aussehen, JavaScript bei Bedarf das Verhalten. Ein Quellcode-Repository verwaltet Dateien und Änderungen. Es ist nicht automatisch schon die laufende Website; dafür braucht es eine Veröffentlichungsfunktion oder einen angeschlossenen Hoster.", "Diese Bausteine können bei einem Anbieter liegen, müssen es aber nicht. Ein Baukasten bündelt vieles, während eigener Code mehr Gestaltungsfreiheit mit eigenen Betriebsaufgaben verbindet. Eine reine Informationsseite benötigt nicht automatisch eine Datenbank. Benutzerkonten, gespeicherte Anfragen oder Bestellungen verändern die Anforderungen deutlich."], source: { title: "MDN: Grundlagen der Website-Veröffentlichung", url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Your_first_website/Publishing_your_website" } },
      { id: "prototyp", title: "Baue die erste Version ohne laufende Kosten.", paragraphs: ["Lege einen neuen Ordner an. Speichere den folgenden Inhalt darin mit einem einfachen Texteditor als index.html in UTF-8. Öffne die Datei per Doppelklick. Der Link springt nur zum Kontaktabschnitt; es werden keine Anfragen übertragen. Passe danach Überschrift, Nutzen und Beschreibung an. Lass den sichtbaren Entwurfshinweis stehen, bis du die Seite fachlich geprüft hast."], code: `<!doctype html>
<html lang="de">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Mein Angebot – lokaler Entwurf</title>
  <style>
    body { font:18px/1.7 system-ui; color:#10123f; margin:40px auto;
      padding:0 20px; max-width:780px; }
    h1 { line-height:1.15; font-size:clamp(32px,6vw,54px); }
    section { margin:36px 0; }
    a { color:inherit; text-underline-offset:4px; }
    a:focus-visible { outline:3px solid #10123f; outline-offset:5px; }
  </style>
</head>
<body>
  <header><p>Lokaler Entwurf · Fiktives Beispiel</p>
    <h1>Weniger Papierarbeit. Mehr Zeit für deinen Betrieb.</h1>
    <p>Hier beschreibst du dein Angebot in einem klaren Satz.</p>
    <a href="#kontakt">So geht es weiter</a>
  </header>
  <main>
    <section aria-labelledby="nutzen"><h2 id="nutzen">Dein Nutzen</h2>
      <ul><li>Informationen schneller finden.</li>
      <li>Wiederkehrende Schritte vereinfachen.</li></ul>
    </section>
    <section aria-labelledby="kontakt"><h2 id="kontakt">Kontakt</h2>
      <p>Hier ergänzt du später deinen geprüften Kontaktweg.</p>
      <p>Dieser Entwurf versendet keine Daten.</p>
    </section>
  </main>
  <footer><p>Nicht zur geschäftlichen Veröffentlichung freigegeben.</p></footer>
</body>
</html>` },
      { id: "testen", title: "Prüfe das Ergebnis, bevor du Technik dazukaufst.", steps: ["Öffne die Datei erneut nach einer Änderung. Wird der neue Text angezeigt? Falls nicht, prüfe Dateiendung, Speicherort und Browseraktualisierung.", "Verkleinere das Browserfenster. Der Text soll umbrechen, ohne horizontal über die Seite hinauszulaufen. Teste zusätzlich eine vergrößerte Schrift beziehungsweise Browser-Zoom.", "Bediene den Link nur mit Tabulator und Enter. Der Fokus muss erkennbar sein und der Sprung zum Kontaktabschnitt funktionieren.", "Lass eine andere Person Angebot und nächsten Schritt erklären. Unverständliche Formulierungen überarbeitest du vor dekorativen Effekten.", "Erstelle eine Veröffentlichungsliste: freigegebene Inhalte, passende Domain, Hosting, HTTPS, tatsächlicher Kontaktweg und die für deinen Auftritt geklärten rechtlichen Informationen."] },
      { id: "weiter", title: "Vom Entwurf zur erreichbaren Website.", paragraphs: ["Für den nächsten Schritt veröffentlichst du zunächst eine rein fiktive Testseite beim passenden Hoster. Danach verbindest du eine eigene Adresse. So prüfst du Inhalt, Hosting und Domain nacheinander und suchst bei Problemen nicht gleichzeitig an drei Stellen.", "Halte Domain und wichtige Konten unter deiner Kontrolle. Dokumentiere, wer die Seite ändern darf, wo der vollständige Quellstand liegt und wie eine funktionierende Version wiederhergestellt wird. Eine schöne Übergabe ohne diese Informationen macht spätere Änderungen unnötig abhängig."] },
    ],
    checklist: ["Das Angebot ist ohne Erklärung verständlich.", "Die lokale HTML-Datei lässt sich öffnen und ändern.", "Darstellung und Tastaturbedienung wurden geprüft.", "Veröffentlichung und rechtliche Freigabe sind vom Prototyp getrennt."],
    limits: "Der Beispielcode ist ein Lernprototyp, kein vollständiger geschäftlicher Webauftritt. Er enthält weder ein versendendes Formular noch fertige rechtliche Texte oder eine Sicherheitsfreigabe.",
    service: "Wir helfen dir vom Angebot bis zur erreichbaren Website: verständliche Struktur, passender technischer Aufbau und eine Übergabe, mit der du die Kontrolle behältst.",
    related: ["website-hosting-verstehen", "domain-richtig-verbinden", "website-mit-ki-erstellen"],
  },
  {
    number: 14, slug: "domain-richtig-verbinden", category: "Websites & Schnittstellen",
    title: "Deine Adresse im Netz: Domain verbinden, ohne die Firmen-Mail lahmzulegen.",
    description: "Was Domain, DNS und Hosting verbindet – und wie du eine neue Website-Adresse testest, während bestehende E-Mails weiterlaufen.",
    lead: "Die Website zieht um, plötzlich kommen keine E-Mails mehr an. Dahinter steckt oft keine große technische Katastrophe, sondern eine zu großzügige Änderung an den Domaineinstellungen. Wer die Zuständigkeiten auseinanderhält, kann die neue Website gezielt verbinden und andere Dienste unangetastet lassen.",
    result: "Ein dokumentierter DNS-Änderungsplan und eine geprüfte Test-Subdomain, bevor du eine bestehende Firmenadresse umstellst.",
    level: "Praxisanleitung · Domain & DNS",
    prerequisites: ["Berechtigter Zugriff auf deine Domainverwaltung und deinen Hoster", "Eine bereits unter der Anbieteradresse funktionierende Testwebsite", "Übersicht über bestehende Website-, Mail- und sonstige Domaineinträge", "Eine freie Test-Subdomain und ein festgelegter Rückweg"],
    sections: [
      { id: "rollen", title: "Wer verwaltet die Adresse, wer beantwortet die Anfrage?", paragraphs: ["Der Registrar verwaltet die Domainregistrierung. Die autoritativen Nameserver geben die gültigen DNS-Antworten aus. Der Webhoster liefert die Website. Dein Mailanbieter nimmt Nachrichten entgegen. Ein Anbieter kann mehrere dieser Rollen übernehmen. Trotzdem bleibt eine Änderung am Webziel etwas anderes als ein Wechsel aller Nameserver.", "A- und AAAA-Einträge verweisen auf IPv4- beziehungsweise IPv6-Adressen. Ein CNAME verweist auf einen anderen DNS-Namen. MX-Einträge betreffen den Mail-Empfang; TXT-Einträge werden unter anderem für Nachweise und Mailrichtlinien verwendet. Kopiere niemals eine IP-Adresse oder einen Nachweis aus einer fremden Anleitung als eigenes Ziel."], source: { title: "Cloudflare: DNS-Eintragstypen erklärt", url: "https://developers.cloudflare.com/dns/manage-dns-records/reference/dns-record-types/" } },
      { id: "bestand", title: "Erst den Bestand festhalten, dann ändern.", steps: ["Notiere Domaininhaber, Registrar, zuständigen DNS-Anbieter und erreichbare Wiederherstellungsadresse. Sichere die Konten mit zusätzlichem Anmeldeschutz.", "Exportiere die aktuelle DNS-Zone, sofern dein Anbieter das unterstützt. Ergänze Screenshots der relevanten Einträge, TTL-Werte und Nameserver. Bewahre die Übersicht geschützt auf.", "Markiere Website, Mail und Verifizierungen getrennt. SPF, DKIM, DMARC und MX bleiben bei einer reinen Website-Umstellung grundsätzlich außerhalb dieses Änderungsumfangs.", "Prüfe eine unbenutzte Testadresse wie test.deine-domain.example. Der Name ist hier nur ein Platzhalter: Verwende eine Subdomain deiner eigenen Domain, die noch keinen Dienst trägt.", "Notiere den erwarteten neuen Eintrag und die vorherige Konfiguration. Ändere nicht mehrere bestehende Dienste gleichzeitig."] },
      { id: "verbinden", title: "Die Testadresse gezielt anschließen.", steps: ["Füge die eigene Testadresse zuerst beim Hoster als benutzerdefinierte Domain hinzu. Folge dessen angezeigtem Nachweis und DNS-Ziel, nicht nur einer allgemeinen Anleitung.", "Lege beim zuständigen DNS-Anbieter ausschließlich die verlangten Einträge für diese Adresse an. Prüfe Name, Typ und Wert einzeln; ein CNAME-Ziel enthält kein https:// und keinen URL-Pfad.", "Bei einer bereits belegten Adresse erst den Konflikt klären. A, AAAA und CNAME dürfen nicht beliebig parallel für denselben Namen kombiniert werden.", "Warte, bis der Hoster Domain und HTTPS-Zertifikat als bereit meldet. DNS-Caches können zwischenzeitlich unterschiedliche Antworten liefern. Wiederholte spontane Änderungen erschweren die Fehlersuche.", "Rufe die Testadresse mit HTTPS über zwei unterschiedliche Verbindungen auf, beispielsweise Heimnetz und Mobilfunk. Kontrolliere Inhalt, Zertifikatswarnungen und Weiterleitungen."] },
      { id: "anbieter", title: "Nicht jeder Hoster verlangt dieselbe Verbindung.", paragraphs: ["Ein Beispiel ist Cloudflare Pages: Eine Subdomain kann über einen CNAME bei einem externen DNS-Anbieter angebunden werden, nachdem sie dem Pages-Projekt zugeordnet wurde. Für die Stammdomain verlangt der beschriebene Pages-Weg dagegen eine Cloudflare-Zone mit entsprechenden Nameservern. Ein Nameserverwechsel ist deshalb keine beiläufige Abkürzung für Anfänger.", "Wenn ein Anbieter einen solchen Wechsel fordert, brauchst du vorher eine vollständige Übernahme der DNS-Zone und einen Plan für alle bestehenden Dienste. Für eine erste Testwebsite ist häufig die zusätzliche Subdomain der übersichtlichere Schritt. Die genaue Entscheidung hängt von deinem Anbieter ab."], source: { title: "Cloudflare Pages: eigene Domains und Subdomains", url: "https://developers.cloudflare.com/pages/configuration/custom-domains/" } },
      { id: "abnahme", title: "Nach der Website auch die unveränderten Dienste prüfen.", paragraphs: ["Sende eine harmlose Testmail von einer externen Adresse an dein Postfach und antworte darauf. Prüfe ebenfalls andere bekannte Dienste unter der Domain. Dieser Funktionstest ergänzt die Kontrolle, dass du deren Einträge nicht verändert hast; er ersetzt keine vollständige Prüfung der Mailkonfiguration.", "Für den eigentlichen Umzug legst du anschließend ein überschaubares Änderungsfenster fest. Alte Website und dokumentierte DNS-Werte bleiben für den Rückweg verfügbar. Domainverlängerung, Zahlungsweg und Kontaktadresse gehören in den Kalender beziehungsweise die Betriebsübersicht – eine fertige Website hilft wenig, wenn ihre Adresse ausläuft."] },
    ],
    checklist: ["Die bisherigen Einträge und Zuständigkeiten sind gesichert.", "Es wurden nur die geplanten Webeinträge geändert.", "Testadresse und HTTPS funktionieren über mehr als einen Zugang.", "Mailtest, Rückweg und Domainverlängerung sind dokumentiert."],
    limits: "Die Anleitung beschreibt einen kontrollierten Einstieg. DNSSEC, bestehende komplexe Mailkonfigurationen oder ein Nameserverwechsel benötigen einen eigenen, anbieterspezifischen Plan. Es gibt keine pauschale Umschaltzeit für alle Netze.",
    service: "Wir verbinden deine Website mit der richtigen Adresse und planen einen Umzug so, dass Website, E-Mail und weitere Dienste getrennt geprüft werden.",
    related: ["website-hosting-verstehen", "website-sicherheit", "weg-zur-eigenen-website"],
  },
  {
    number: 15, slug: "website-hosting-verstehen", category: "Websites & Schnittstellen",
    title: "Der Code ist fertig. Warum ist deine Website noch nicht online?",
    description: "Welches Hosting zu welcher Website passt und wie du eine kleine HTML-Seite veröffentlichst – ohne gleich einen eigenen Server zu betreiben.",
    lead: "Eine Website auf deinem Rechner ist wie eine fertig gestaltete Broschüre auf deinem Schreibtisch: Sie existiert, aber deine Kunden können sie noch nicht erreichen. Hosting macht sie verfügbar. Welche Art du brauchst, hängt weniger vom Design ab als davon, was die Seite tatsächlich tun soll.",
    result: "Eine veröffentlichte, rein fiktive HTML-Testseite unter einer Anbieteradresse und ein Hosting-Plan, der zu deinen späteren Funktionen passt.",
    level: "Einstieg · Veröffentlichung",
    prerequisites: ["Ein Ordner mit einer funktionierenden index.html, beispielsweise aus unserem Website-Einstieg", "Nur ausdrücklich zur Veröffentlichung bestimmte Testinhalte", "Für den Beispielweg ein eigenes Cloudflare-Konto mit geprüftem Tarif", "Eine separat aufbewahrte Kopie aller hochzuladenden Dateien"],
    sections: [
      { id: "arten", title: "Drei Arten von Websites, drei unterschiedliche Aufgaben.", paragraphs: ["Eine statische Website liefert vorbereitete Dateien aus. Das passt beispielsweise zu einer Informationsseite ohne Anmeldung und ohne gespeicherte Eingaben. Ein Content-Management-System wie WordPress braucht zusätzlich seine passende Laufzeit, Datenbank und einen Updateprozess. Eine eigene Webanwendung mit Benutzerkonten oder Datenverarbeitung benötigt wiederum die Laufzeit und Dienste, die ihre Architektur vorsieht.", "Ein Anbieter kann mehrere Varianten unterstützen. Daraus folgt aber nicht, dass beliebiger Code auf jedem Tarif läuft. Ein Ordner mit React-Quellcode ist noch nicht immer ein veröffentlichungsfertiger Dateisatz. Manche Projekte brauchen einen Build, andere dauerhaft serverseitige Funktionen. Lass dir diese Unterscheidung vor dem Vertragsabschluss erklären."], source: { title: "MDN: statische und dynamische Websites", url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Server-side/First_steps/Client-Server_overview" } },
      { id: "auswahl", title: "Vergleiche den Betrieb, nicht nur den Monatspreis.", steps: ["Schreibe alle Funktionen auf: reine Inhalte, Formular, Anmeldung, Dateiupload, Datenbank, Hintergrundaufgaben. Ordne jeder Funktion einen verantwortlichen Dienst zu.", "Prüfe unterstützte Laufzeiten, kommerzielle Nutzung, eigene Domains und HTTPS. Ein Gratisangebot ist nicht automatisch für eine geschäftliche Website freigegeben.", "Vergleiche enthaltene Leistung, Nutzungsgrenzen, Mehrverbrauch, Backups und Wiederherstellung. Ein Kostenalarm ist nicht automatisch eine harte Ausgabensperre.", "Kläre Datenverarbeitung, Unterauftragnehmer und gegebenenfalls benötigte Regionen passend zu deinem Vorhaben. Eine Domainendung sagt nichts über den tatsächlichen Speicherort aus.", "Prüfe, ob du Quellcode, Inhalte und Daten exportieren kannst. Dokumentiere, was bei einem Anbieterwechsel mitgenommen werden muss."] },
      { id: "upload", title: "Eine einfache Seite per Datei-Upload veröffentlichen.", paragraphs: ["Wir verwenden für das Lernbeispiel Cloudflare Pages Direct Upload. Prüfe vorher die aktuellen Bedingungen und Limits. Dieser Weg ist für fertige statische Dateien gedacht. Ein Direct-Upload-Projekt lässt sich später nicht einfach auf Git-Integration umstellen; dafür ist ein neues Projekt nötig. Für regelmäßig gemeinsam gepflegten Code solltest du diese Entscheidung vorab treffen."], steps: ["Erstelle einen sauberen Veröffentlichungsordner. Darin liegen index.html und nur die tatsächlich benötigten Bilder oder Styles – keine Zugangsdaten, internen Dokumente oder Entwicklungsdateien.", "Öffne im Cloudflare-Dashboard Workers & Pages und wähle den Pages-Weg für einen direkten Datei-Upload. Die genaue Menübenennung kann sich ändern.", "Vergib einen Projektnamen und lade den Ordner oder die ZIP-Datei hoch. index.html muss in der Wurzel des hochgeladenen Seiteninhalts liegen.", "Starte die Veröffentlichung und öffne die zugewiesene pages.dev-Adresse. Diese Adresse ist öffentlich; ein Testname ist kein Zugriffsschutz.", "Ändere lokal einen eindeutig erkennbaren Testsatz. Veröffentliche im selben Projekt eine neue Version und prüfe, ob genau diese Änderung online erscheint."], source: { title: "Cloudflare Pages: Direct Upload", url: "https://developers.cloudflare.com/pages/get-started/direct-upload/" } },
      { id: "pruefen", title: "Eine erreichbare Startseite ist erst der erste Test.", paragraphs: ["Öffne jede interne Seite direkt über ihre Adresse und lade sie neu. Prüfe Bilder, Schrift, Umlaute, Handyansicht und einen bewusst falschen Pfad. Eine Anwendung kann auf der Startseite funktionieren und beim direkten Aufruf einer Unterseite trotzdem scheitern. Notiere erwartetes und tatsächliches Verhalten.", "Das Beispiel enthält keine Datenbank und keinen Formularempfang. Ein sichtbarer Absende-Button allein baut diese Funktionen nicht ein. Auch das Hochladen eines Ordners namens functions über einen einfachen Dashboard-Upload ersetzt keine passende serverseitige Bereitstellung. Sobald du Eingaben verarbeiten willst, gehört diese Funktion in die Hostingplanung."] },
      { id: "kosten", title: "Gratis ist eine Tarifbedingung, kein Architekturmerkmal.", paragraphs: ["Ein konkretes Beispiel: Vercel beschreibt seinen Hobby-Tarif für persönliche, nicht kommerzielle Nutzung. Für einen geschäftlichen Auftritt darfst du daher nicht allein aus einem funktionierenden Test schließen, dass der gleiche Tarif passt. Prüfe die aktuellen Anbieterbedingungen vor dem produktiven Einsatz.", "Für die Budgetplanung trennst du Domain, Hosting, Mail, zusätzliche Dienste und laufende Betreuung. Eine sehr kleine Website braucht nicht zwingend einen selbst verwalteten Server. Bei individuellen Anwendungen kann ein betreuter Aufbau sinnvoll sein, weil Einrichtung, Fehlersuche und Updates ebenfalls Zeit kosten."], source: { title: "Vercel: Einsatzgrenzen des Hobby-Tarifs", url: "https://vercel.com/docs/plans/hobby" } },
    ],
    checklist: ["Der Hostingtyp passt zu den tatsächlichen Funktionen.", "Die Testseite ist unter der Anbieteradresse erreichbar.", "Direkte Unterseitenaufrufe und eine neue Veröffentlichung wurden geprüft.", "Tarif, öffentliche Inhalte und Rückweg sind geklärt."],
    limits: "Cloudflare Pages ist hier ein nachvollziehbares Lernbeispiel, keine pauschale Anbieterempfehlung. Das Veröffentlichen statischer Dateien richtet weder ein geschütztes Kundenportal noch einen zuverlässigen Formularprozess ein.",
    service: "Wir wählen mit dir einen passenden Betrieb, verbinden Domain und Veröffentlichung und klären vorab, welche Zusatzdienste deine Website wirklich braucht.",
    related: ["domain-richtig-verbinden", "website-mit-ki-erstellen", "website-api-anbindung"],
  },
  {
    number: 16, slug: "website-mit-ki-erstellen", category: "Websites & Schnittstellen",
    title: "Mit KI zur eigenen Website: schnell zum Entwurf, bewusst zur fertigen Lösung.",
    description: "Ein brauchbarer Vibe-Coding-Ablauf: kleines Ziel, klare Vorgaben, nachvollziehbare Änderungen und Tests statt blindem Vertrauen in die Vorschau.",
    lead: "Du beschreibst deine Idee, und wenige Minuten später steht eine erste Seite. Das kann ein enormer Einstiegsvorteil sein. Die entscheidende Frage kommt danach: Funktioniert sie auch für Besucher, auf dem Handy und nach der nächsten Änderung? Mit einem klar begrenzten Auftrag wird KI zum hilfreichen Werkzeug statt zur Quelle ständig neuer Baustellen.",
    result: "Ein lokal überprüfbarer Website-Entwurf, ein wiederverwendbares Briefing und eine eigene Abnahmecheckliste für KI-generierte Änderungen.",
    level: "Einstieg · KI-gestützte Umsetzung",
    prerequisites: ["Ein KI-Werkzeug, dessen Bedingungen du für deine Inhalte geprüft hast", "Texteditor und Browser; für dieses Beispiel keine bezahlte Programmierschnittstelle", "Nur fiktive Inhalte und keine Zugangsdaten oder vertraulichen Kundendokumente", "Ein eigener Projektordner und eine Sicherung jeder akzeptierten Version"],
    sections: [
      { id: "eingrenzen", title: "Beschreibe eine Aufgabe, nicht gleich dein ganzes Unternehmen.", paragraphs: ["Beginne mit einer Informationsseite ohne Anmeldung, Zahlung und Datenspeicherung. Nenne Zielgruppe, Angebot, Ton und den gewünschten nächsten Schritt. Sage ausdrücklich, was noch nicht gebaut werden soll. Sonst entstehen schnell ein funktionsloses Kontaktformular oder unnötige Bibliotheken, die nachher mitbetrieben werden müssen.", "Das Design darf inspirieren, aber der erste Erfolg ist eine verständliche Seite. Du solltest die gelieferten Dateien benennen können und wissen, wie du sie lokal öffnest. Wenn ein Werkzeug stattdessen ein umfangreiches Projekt erzeugt, lass dir den zusätzlichen Bedarf begründen, bevor du neue Dienste oder Konten anlegst."] },
      { id: "briefing", title: "Ein Prompt, mit dem du klein und überprüfbar startest.", paragraphs: ["Passe Zielgruppe und Angebot im folgenden Briefing an. Verwende zunächst ausgedachte Inhalte. Der Auftrag legt bewusst fest, dass die erste Version lokal funktioniert und keine Besucherangaben überträgt."], code: `Erstelle eine deutschsprachige Informationsseite für ein fiktives Angebot.
Zielgruppe: kleine Handwerksbetriebe.
Nutzen: weniger Suchaufwand bei digitalen Unterlagen.
Nächster Schritt: zum Kontaktabschnitt springen, noch keine Daten versenden.

Liefere genau zwei Dateien: index.html und styles.css.
Verwende semantisches HTML und normales CSS.
Keine externen Schriftarten, Tracker, Bibliotheken oder Downloads.
Kein Login, keine Datenbank, kein Formular und keine erfundenen Referenzen.
Kennzeichne den Stand sichtbar als lokalen Entwurf.

Die Seite soll ab 320 Pixel Breite ohne seitliches Scrollen funktionieren.
Links müssen per Tastatur erreichbar und Fokuszustände sichtbar sein.
Beschreibe, wie ich die Dateien lokal öffne und das Ergebnis teste.
Erkläre separat, was vor einer geschäftlichen Veröffentlichung noch fehlt.` },
      { id: "ablauf", title: "So arbeitest du Änderungen kontrolliert ein.", steps: ["Speichere die ausgegebenen Dateien in einem neuen Ordner. Prüfe, dass die HTML-Datei genau auf die gelieferte CSS-Datei verweist, und öffne index.html im Browser.", "Lies Texte und Links selbst. Entferne erfundene Bewertungen, Garantien, Kundenlogos und Kontaktangaben, statt sie für einen professionellen Eindruck stehen zu lassen.", "Prüfe eine Sache nach der anderen: Inhalt, schmale Darstellung, Tastaturbedienung, erst danach kleine Gestaltungseffekte.", "Beschreibe Fehler mit Ausgangssituation und Erwartung: „Bei 360 Pixel Breite läuft die Überschrift rechts heraus. Ändere nur den Umbruch; die Desktopdarstellung soll bleiben.“", "Fordere eine Liste der geänderten Stellen an. Sichere den funktionierenden Stand vor jeder weiteren Änderung unter einer eindeutigen Versionsbezeichnung.", "Wenn neue Pakete, Terminalbefehle oder externe Dienste vorgeschlagen werden, kläre zuerst Zweck, Herkunft, Kosten und Rückweg. Unverstandene Befehle nicht einfach in ein produktives Projekt übernehmen."] },
      { id: "abnahme", title: "Teste das, was die Vorschau nicht beweist.", paragraphs: ["Eine attraktive Bildschirmansicht beweist weder eine funktionierende Datenübertragung noch saubere Zugriffsrechte. Prüfe die Seite mit Tastatur und vergrößerter Schrift, klicke jeden Link und lies den Quelltext auf unerwartete externe Adressen. Im Netzwerkbereich der Browser-Entwicklerwerkzeuge kannst du beim Neuladen erkennen, welche Dienste tatsächlich aufgerufen werden.", "Nutze für den einfachen lokalen Entwurf die Prüfpunkte aus dem Website-Einstieg. Bei einem größeren Projekt kommen reproduzierbarer Build, Abhängigkeiten und eine getrennte Testumgebung hinzu. Lasse einen fehlgeschlagenen Test nicht durch das Entfernen der Prüfung „reparieren“. Die Anforderung soll erfüllt werden, nicht nur die Fehlermeldung verschwinden."] },
      { id: "grenze", title: "Der Wechsel zur Anwendung ist eine bewusste Entscheidung.", paragraphs: ["Sobald die Website Konten, interne Informationen, Uploads oder Zahlungen verwaltet, reicht reine Oberflächengestaltung nicht mehr. Dann müssen unter anderem serverseitige Berechtigungen, Fehlermeldungen, Speicherung und Betrieb geplant und getestet werden. Ein versteckter Button oder eine unbekannte URL schützt keine Daten.", "KI kann beim Schreiben und Prüfen helfen. Sie übernimmt aber nicht automatisch die Verantwortung für das Ergebnis. Gerade hier kann eine gezielte technische Abnahme sinnvoller sein als ein kompletter Neubau: Du behältst deinen Entwurf, und die kritischen Stellen werden fachlich ergänzt."] },
    ],
    checklist: ["Der Auftrag begrenzt Funktionen und Datenübertragung ausdrücklich.", "Der Entwurf läuft lokal und enthält keine erfundenen Leistungsnachweise.", "Links, Fokus, schmale Darstellung und externe Aufrufe wurden geprüft.", "Eine funktionierende Vorversion und offene Aufgaben sind dokumentiert."],
    limits: "Der Workflow ist für einen überschaubaren Website-Entwurf gedacht. Er ersetzt keine Sicherheitsprüfung einer Anwendung und verspricht weder fehlerfreien KI-Code noch eine fertige geschäftliche Website auf Knopfdruck.",
    service: "Du hast schon einen KI-Entwurf? Wir helfen beim Prüfen, Fertigstellen und Veröffentlichen – oder entwickeln mit dir zuerst den passenden Aufbau, bevor zusätzliche Technik dazukommt.",
    related: ["weg-zur-eigenen-website", "website-sicherheit", "website-api-anbindung"],
  },
  {
    number: 17, slug: "website-sicherheit", category: "Websites & Schnittstellen",
    title: "HTTPS reicht nicht: Wie du deine Website alltagstauglich absicherst.",
    description: "Ein konkreter Sicherheits- und Betriebscheck für kleine Websites: Konten, veröffentlichte Dateien, Updates, Wiederherstellung und Zuständigkeiten.",
    lead: "Du musst nicht selbst zum Sicherheitsexperten werden, um bei deiner Website die richtigen Fragen zu stellen. Schon ein klarer Überblick über Konten, Dateien und Zuständigkeiten verhindert vermeidbare Probleme. Entscheidend ist, dass du nicht nur den heutigen Onlinezustand kennst, sondern auch den Weg zurück, wenn etwas schiefgeht.",
    result: "Eine dokumentierte Basisprüfung deiner eigenen Website und ein nachvollziehbarer Plan für Änderungen, Ausfälle und Wiederherstellung.",
    level: "Praxisanleitung · Sicherheit & Betrieb",
    prerequisites: ["Berechtigter Zugriff auf die eigene Website und ihre Verwaltung", "Übersicht über Domain, Hosting, Quellcode und verbundene Dienste", "Ein gesicherter Ausgangsstand; für Funktionstests nur künstliche Daten", "Keine Sicherheitsversuche gegen fremde Systeme"],
    sections: [
      { id: "zugriff", title: "Schütze zuerst die Konten, die alles verändern können.", steps: ["Liste Domainverwaltung, Hosting, Codeverwaltung, Mail und gegebenenfalls CMS als getrennte Zugänge auf. Notiere Besitzer und die Personen, die wirklich Änderungen benötigen.", "Verwende persönliche Konten, eindeutige Passwörter beziehungsweise unterstützte Passkeys und einen zusätzlichen Faktor, wo verfügbar. Geteilte Administratorkonten erschweren die Zuordnung und das spätere Entziehen von Zugriff.", "Sichere Wiederherstellungscodes geschützt außerhalb des Kontos. Prüfe, ob die Wiederherstellungsadresse unabhängig erreichbar bleibt, falls die eigene Domain ausfällt.", "Entferne nicht mehr benötigte Einladungen und Zugänge nach abgestimmter Prüfung. Halte mindestens einen kontrollierten Wiederherstellungsweg für den Verantwortlichen offen.", "Prüfe Benachrichtigungen zu Anmeldung, Domainablauf und Abrechnung. Sicherheitsmeldungen helfen nur, wenn sie jemand erhält und bearbeitet."] },
      { id: "dateien", title: "Alles im Browser ist grundsätzlich einsehbar.", paragraphs: ["JavaScript, HTML und öffentlich ausgelieferte Dateien sind kein Versteck für Passwörter. Ein API-Schlüssel wird nicht dadurch geheim, dass sein Variablenname kompliziert ist oder er in einem minimierten Skript steht. Besonders kritisch sind vollständige Projektordner, die versehentlich statt des vorgesehenen Veröffentlichungsverzeichnisses hochgeladen werden.", "Prüfe den Dateisatz vor dem Upload: keine .env-Dateien, Sicherungsarchive, privaten PDFs, internen Notizen oder vertraulichen Testdaten. Gehe außerdem durch bereits veröffentlichte Dateien und die Änderungshistorie. Ist ein Geheimnis öffentlich geworden, reicht Löschen allein nicht: Zugang sperren oder austauschen, Reichweite prüfen und betroffene Verarbeitung bewerten."], source: { title: "OWASP: Umgang mit technischen Geheimnissen", url: "https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html" } },
      { id: "funktionen", title: "Die Verbindung und die Anwendung getrennt prüfen.", paragraphs: ["HTTPS schützt die Übertragung zwischen Browser und dem jeweiligen Server. Es beweist nicht, dass jede Person nur ihre eigenen Daten sehen kann, dass Inhalte richtig gespeichert werden oder dass keine unerwünschten Drittanbieter beteiligt sind. Auch eine mit HTTPS erreichbare Vorschau kann für die ganze Welt offen sein.", "Für eine reine Informationsseite prüfst du HTTPS, Weiterleitungen, externe Ressourcen und veröffentlichte Inhalte. Für eine Anwendung brauchst du zusätzlich Tests mit verschiedenen Rollen: abgemeldet, normaler Benutzer und Admin. Prüfungen im Browser sind dabei nur die Oberfläche; der Server muss jede geschützte Operation selbst berechtigen."] },
      { id: "aenderungen", title: "Eine neue Version braucht einen überprüfbaren Rückweg.", steps: ["Sichere vor einer Änderung den vollständigen Quellstand und die notwendigen Konfigurationen. Bei CMS oder Anwendungen gehören relevante Datenbestände dazu; ein Screenshot ist keine Sicherung.", "Teste die Änderung zunächst in einer getrennten Umgebung ohne echte Kundendaten. Kontrolliere auch Funktionen, die du nicht absichtlich verändert hast.", "Notiere freigegebene Version, Datum und Verantwortlichen. Veröffentliche eine überschaubare Änderung und prüfe danach Startseite, Unterseiten und den tatsächlichen Kontaktweg.", "Übe an einer Testumgebung die Rückkehr zum vorherigen Stand. Bei Datenbanken kann ein Code-Rollback allein unzureichend sein; Datenänderungen brauchen einen eigenen Rückweg.", "Richte regelmäßige Update- und Funktionskontrollen ein. Sicherheitsrelevante Meldungen warten nicht automatisch bis zum nächsten monatlichen Routinetermin."] },
      { id: "notfall", title: "Schreibe eine Notiz, die auch im Ausfall hilft.", paragraphs: ["Deine Betriebsnotiz enthält Anbieter, zuständige Personen, gesicherten Quellstand, Wiederherstellungsverfahren und den Weg zum Support. Passwörter selbst gehören in eine geeignete geschützte Verwaltung, nicht als Klartext in dieselbe Notiz. Gib der Vertretung genau die Rechte, die sie im vereinbarten Fall braucht.", "Miss Erreichbarkeit und Funktionsfähigkeit getrennt. Eine Startseite kann erreichbar sein, während Anfragen im Hintergrund scheitern. Ein regelmäßiger Test mit eindeutig erkennbaren künstlichen Angaben zeigt, ob der fachliche Ablauf noch funktioniert. Dokumentiere anschließend, wo diese Testdaten entfernt werden müssen."] },
    ],
    checklist: ["Konten, Rechte und Wiederherstellungswege sind geprüft.", "Veröffentlichte Dateien enthalten keine vertraulichen Inhalte oder Zugangsdaten.", "HTTPS und die tatsächlich angebotenen Funktionen wurden getrennt geprüft.", "Sicherung, Rückweg und Verantwortlichkeit sind dokumentiert."],
    limits: "Diese Basisprüfung ist kein Penetrationstest und keine Zertifizierung. Ein guter Check reduziert bestimmte Risiken, beweist aber keine vollständige Sicherheit oder pauschale rechtliche Konformität.",
    service: "Wir prüfen den Aufbau und die Betriebsabläufe deiner Website, priorisieren konkrete Lücken und helfen bei einer verständlichen, wartbaren Lösung mit klaren Zuständigkeiten.",
    related: ["website-hosting-verstehen", "website-api-anbindung", "selber-machen-oder-machen-lassen"],
  },
  {
    number: 18, slug: "website-api-anbindung", category: "Websites & Schnittstellen",
    title: "Vom Formular direkt in dein System: Was eine API für dich erledigen kann.",
    description: "Informationen einmal erfassen und gezielt weitergeben: eine erste Schnittstellenanfrage ausprobieren und verstehen, was einen verlässlichen Ablauf ausmacht.",
    lead: "Eine neue Anfrage kommt über deine Website. Jemand kopiert sie in eine Tabelle und trägt sie danach ins nächste Programm ein. Eine Schnittstelle kann diese Übergaben vereinfachen. Der eigentliche Nutzen ist nicht „eine API“, sondern ein Ablauf, in dem Informationen vollständig ankommen und Fehler nicht unbemerkt bleiben.",
    result: "Eine nachvollziehbare Testanfrage an einen öffentlichen Echo-Dienst und ein Plan für die spätere Übergabe in dein eigenes Zielsystem.",
    level: "Technischer Einstieg · Schnittstellen",
    prerequisites: ["Ein Terminal mit curl; der gezeigte Mehrzeiler ist für macOS oder eine Linux-Shell gedacht", "Internetverbindung und ausschließlich die künstlichen Beispieldaten", "Für die spätere echte Anbindung: Dokumentation und autorisierter Testzugang zum Zielsystem", "Die Bereitschaft, Erfolgsfälle und Fehlerfälle getrennt zu testen"],
    sections: [
      { id: "ablauf", title: "Was soll nach dem Absenden wirklich passiert sein?", paragraphs: ["Beschreibe zuerst den fachlichen Endzustand: „Eine Serviceanfrage erscheint genau einmal mit Betreff, Kategorie und Rückkontakt im zuständigen System.“ Liste die benötigten Angaben und ihre Ziel-Felder auf. Eine frei formulierte Beschreibung und eine interne Kundennummer sind nicht einfach austauschbar, nur weil beide als Text übertragen werden können.", "Eine API ist die vereinbarte Programmschnittstelle des Zielsystems. Adresse, Methode, Datenformat und Berechtigung legen fest, wie eine Anfrage aussehen muss. Eine öffentlich dokumentierte API ist nicht automatisch ohne Anmeldung nutzbar oder in jedem Tarif enthalten. Kläre diese Punkte vor dem Formularbau."] },
      { id: "test", title: "Eine erste Übertragung ohne echte Kundendaten ausprobieren.", paragraphs: ["httpbin ist ein öffentlicher Dienst, der Testanfragen und Antworten sichtbar macht. Der folgende Aufruf sendet lediglich eine ausgedachte ID und einen Betreff an diesen externen Anbieter. Wie bei jedem Internetaufruf fallen auch Verbindungsdaten an. Sende deshalb keine Kundeninformationen, Zugangsdaten oder Dokumente dorthin. Das Beispiel ist kein Formular-Backend und kein Speichertest."], code: `curl --connect-timeout 10 --max-time 20 --include \\
  --request POST 'https://httpbin.org/post' \\
  --header 'Content-Type: application/json' \\
  --data '{"anfrage_id":"demo-001","betreff":"Fiktiver Test"}'`, source: { title: "httpbin: öffentlicher HTTP-Testdienst", url: "https://httpbin.org/" } },
      { id: "antwort", title: "Die Antwort lesen, statt nur auf einen grünen Haken zu schauen.", steps: ["Führe den unveränderten Aufruf einmal aus. Prüfe zuerst den HTTP-Status, anschließend den Antwortinhalt. Bei Zeitüberschreitung oder Nichterreichbarkeit brich den Versuch ab; deaktiviere keine Zertifikatsprüfung.", "Suche im JSON-Antwortobjekt den Bereich json. Dort sollten anfrage_id und betreff mit den gesendeten Beispielwerten erscheinen.", "Ändere nur den fiktiven Betreff und wiederhole den Aufruf. So erkennst du, welche Werte in deinem Request stehen und was der Dienst zurückliefert.", "Notiere: Dieser Test belegt eine beantwortete Übertragung an einen Echo-Dienst. Er belegt nicht, dass ein CRM einen Datensatz angelegt oder eine Mail zugestellt hat.", "Für die echte Integration ersetzt du nicht einfach die Adresse: Prüfe dokumentierte Methode, Anmeldung, Feldnamen, Typen, Pflichtfelder, Fehlercodes und erwartete Empfangsbestätigung des Zielsystems."] },
      { id: "grenzen", title: "Der Browser bekommt keine geheimen Universalschlüssel.", paragraphs: ["Braucht das Zielsystem einen vertraulichen technischen Schlüssel, gehört er in einen geschützten serverseitigen Ablauf und nicht in das JavaScript der Website. Das Frontend übergibt die erlaubten Angaben an deinen kontrollierten Endpunkt. Dort werden Eingaben geprüft, der Zugriff begrenzt und die Weitergabe mit dem vorgesehenen Zugang ausgeführt.", "Manche APIs unterstützen bewusst öffentliche Browserzugriffe mit eingeschränkten Rechten. Das muss der Anbieter ausdrücklich so vorsehen. CORS regelt bestimmte Zugriffe durch Browser; es ersetzt weder eine Benutzeranmeldung noch eine serverseitige Berechtigungsprüfung. Ein im Terminal erfolgreicher Aufruf kann im Browser deshalb trotzdem scheitern."], source: { title: "MDN: Client und Server verstehen", url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Server-side/First_steps/Client-Server_overview" } },
      { id: "zuverlaessigkeit", title: "Zuverlässig heißt auch: Fehler und Wiederholungen beherrschen.", paragraphs: ["Plane eine eindeutige Vorgangskennung und eine Prüfung gegen doppelte Verarbeitung. Wenn das Zielsystem die Anfrage bereits gespeichert hat, die Antwort aber verloren geht, kann blindes Wiederholen sonst zwei Vorgänge erzeugen. Nutze eine dokumentierte Idempotenzfunktion oder eine abgestimmte eigene Duplikatlogik; eine beliebige ID im JSON reicht dafür allein nicht aus.", "Unterscheide Eingabefehler, fehlende Berechtigung, Rate-Limits und vorübergehende Ausfälle. Nur passende Fälle werden begrenzt und mit Abstand erneut versucht. Offene Übertragungen müssen sichtbar bleiben und eine zuständige Person haben. Protokolliere Vorgangskennung und Ergebnis sparsam, ohne geheime Schlüssel oder unnötige personenbezogene Inhalte in Logs zu kopieren.", "Der Abnahmetest findet im autorisierten Testsystem statt: erfolgreicher Vorgang, fehlendes Pflichtfeld, doppelte Sendung, abgelaufener Zugang und simulierte Nichterreichbarkeit. Als Erfolg zählt der fachlich überprüfte Eingang im Zielsystem, nicht nur eine freundliche Meldung auf der Website."] },
    ],
    checklist: ["Benötigte Angaben sind eindeutig den Ziel-Feldern zugeordnet.", "Request, Status und Antwortinhalt des künstlichen Tests wurden verstanden.", "Vertrauliche Zugänge bleiben außerhalb des Browsercodes.", "Doppelte Sendungen, Ausfälle und offene Vorgänge haben eine definierte Behandlung."],
    limits: "Der Echo-Test ist öffentlich und speichert keine nachgewiesenen Geschäftsvorgänge für dich. Eine echte Integration benötigt einen autorisierten Zielzugang, abgestimmte Verarbeitungsvorgaben und eigene Tests. Manche Systeme lassen die gewünschte Anbindung nicht oder nur eingeschränkt zu.",
    service: "Wir verbinden deine Datenerfassung mit den vorhandenen Systemen und planen nicht nur die erste Übertragung, sondern auch Rückmeldungen, Fehlerbehandlung und Zuständigkeiten.",
    related: ["informationen-mit-formularen-erfassen", "website-sicherheit", "bueroaufgaben-automatisieren"],
  },
]
